on:
  release:
    types: [published]

name: "Release"

jobs:
  release-artifacts:
    name: Create release artifacts
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: ["386", amd64, arm]
        exclude:
          - os: windows
            arch: arm
          - os: darwin
            arch: "386"
          - os: darwin
            arch: arm

    steps:
      - uses: actions/checkout@master
      - name: compile and release binary
        uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
      - name: compile and release library
        uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          build_flags: "--buildmode=c-shared"
          binary_name: "minica.dll"
