on:
  release:
    types: [published]

name: "Release"

jobs:
  release-artifacts:
    name: Create release artifacts
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: ["386", amd64, arm]
        exclude:
          - os: windows
            arch: arm
          - os: darwin
            arch: "386"
          - os: darwin
            arch: arm

    steps:
      - uses: actions/checkout@master

      - name: Set up windows cross compilation
        if: ${{ matrix.os == 'windows' }}
        run: |
          case "${{ matrix.arch }}" in
            "386") echo "CC=i686-w64-mingw32-gcc" >> $GITHUB_ENV ;;
            "amd64") echo "CC=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV ;;
          esac
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "INSTALL_PACKAGES=mingw-w64" >> $GITHUB_ENV

      - name: Set up environment for linux i386/arm dll building
        if: ${{ matrix.os == 'linux' }}
        run: |
          case "${{ matrix.arch }}" in
            'arm')
              echo "INSTALL_PACKAGES=gccgo-6-arm-linux-gnueabi" >> $GITHUB_ENV
              echo "CC=arm-linux-gnueabi-gcc-6" >> $GITHUB_ENV
              ;;
            '386')
              echo "INSTALL_PACKAGES=g++-multilib" >> $GITHUB_ENV
              ;;
          esac
          echo "CGO_ENABLED=1" >> $GITHUB_ENV

      - name: compile and release binary
        uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          pre_command: 'if [[ ! -z "${{ env.INSTALL_PACKAGES }}" ]]; then apt-get update; apt-get install -y "${{ env.INSTALL_PACKAGES }}"; fi'

      - name: compile and release library
        uses: wangyoucao577/go-release-action@v1.30
        if: ${{ matrix.os != 'darwin' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          build_flags: "--buildmode=c-shared"
          binary_name: "minica.dll"
          pre_command: 'if [[ ! -z "${{ env.INSTALL_PACKAGES }}" ]]; then apt-get update; apt-get install -y "${{ env.INSTALL_PACKAGES }}"; fi'
